language: node_js
branches:
  only:
    - master
node_js:
  - '6'
sudo: false
cache:
  directories:
  - "$HOME/.npm"
before_install:
  - npm config set spin false
  - npm install -g phantomjs-prebuilt
  - npm install -g bower
  - phantomjs --version
install:
  - npm install
  - bower install
script:
  - npm test
deploy:
  provider: firebase
  token:
    secure: w6Kl7fTP1R8EwWOw1W1rMNhqFLqgQla6+NmOxbWsT41dOcN8hZGKGeRYWOUBn46HnGhaWz5QPXPwK4eblugDYQU2Fi85K28Z0WaYfD8Bxvg4YZHHGlSpXkflOxgPF2uv2QLccJ8+3OMSrEnFN/L2xW+l31R5BBmPqGnitq/+X6o9WV9p21b83IyjURs09ADFu+xo9KnKwpiAl7c+udj++B1AOknFeBK/xOoZp1jH/f2mAN0rQ6/i2LGl6rmey+YFVrj/IXBVX1v9GoVd659ZSvSo6S+gN0sjwfs28TToa6fSFwtx78tEJUieq6bZf7JVJoBtrMB/rOvlzAoTJn4QrhvZ/2QfAfPBGy23e+2NeRWj0UIo6vU7nPXd5MwZdJGMpnzqJmohxSRenZ7djdzPlvaLHR4ZrYr20W6p9tQ36SSGHEgebH9lE0s+UUgKz32QvUu7LXCHK6+1HXS+hfW19MW3MrRiLkT02qBRVRAOa78AdfzS8AD8eECZQk20wNKMP5U6nFJL9231Etdm4g3gCZwSjF0HE+tibgJq6j6BHGZYD62CG7g0Gwip3E9h6kgiSRzRQ04XEpS7krGru740BK/aYkAeywEpNq4fHtPZ/hpSxwHy8A0+Wxvau9bdyWtfiHJkgpZKLyq95/9HpPBtXesNQfYa3LV+MzA63Fv/L0M=
  message: Deployed from Travis
